/**
 * MigrantCare Kaohsiung — 多語系 UI 字串
 * 支援語言：zh（中文）、en（英文）、id（印尼語）、vi（越南語）、th（泰語）
 * localStorage key：migrant_lang
 */
const LANG_DATA = {
  zh: {
    // 語系選擇頁
    langScreenTitle: '請選擇語言',
    langScreenSubtitle: '選擇後可隨時在主頁切換',

    // 登入 / 註冊頁
    authWelcome: '歡迎使用 MigrantCare',
    authSubtitle: '高雄市移工友善助手',
    loginTitle: '選擇帳號',
    registerTitle: '建立帳號',
    btnLogin: '登入',
    btnRegister: '建立新帳號',
    btnConfirm: '確認',
    btnBack: '返回',
    inputNickname: '暱稱（2–20 字）',
    inputPin: '4 位數字 PIN',
    inputPinConfirm: '再次輸入 PIN',
    labelIdentity: '您的身份',
    identityWorker: '外籍移工',
    identityNewcomer: '新住民',
    identityOther: '其他',
    labelAvatar: '選擇頭像',
    msgPinMismatch: 'PIN 不一致，請重新輸入',
    msgNicknameRequired: '請輸入暱稱（2–20 字）',
    msgPinRequired: '請輸入 4 位數字 PIN',
    msgLoginFail: 'PIN 錯誤，請再試一次',

    // 底部 Tab
    tabHome: '首頁',
    tabMedical: '問診卡',
    tabLabor: '權益速查',
    tabMap: '資源地圖',
    tabTranslate: '對話翻譯',

    // 對話翻譯模組
    translateSubtitle:   '醫生說中文 ↔ 移工說母語，即時翻譯',
    translateHint:       '按下方按鈕開始說話',
    translateDoctorBtn:  '醫護人員說話',
    translatePatientBtn: '移工說話',

    // 首頁
    homeGreeting: '您好',
    homeFamiliarityLabel: '熟悉度',
    homeRankLabel: '段位',
    homeGameSwitch: '地標遊戲',
    homeGameOn: '開啟',
    homeGameOff: '關閉',

    // 段位名稱（5段）
    rankSprout:  '新芽',
    rankGrowing: '成長',
    rankSteady:  '穩健',
    rankSkilled: '熟練',
    rankExpert:  '達人',

    // 分項統計
    homeStatLaborLabel:   '勞工權益',
    homeStatLaborValue:   '已讀 {n}/24 題',
    homeStatSymptomLabel: '問診卡',
    homeStatSymptomValue: '使用 {n} 次',
    homeStatLandmarkLabel:'地標遊戲',
    homeStatLandmarkValue:'訪問 {n} 個地標',
    homeLastLocation:     '最近位置',
    homeNoLocation:       '尚未記錄',
    homeQuickEntry:       '快速入口',
    homeLogout:           '登出',
    homeLogoutConfirm:    '確定要登出嗎？',

    // 勞工權益速查模組
    laborTitle:            '🏛 勞工權益速查',
    laborSelectCategory:   '選擇問題類別',
    laborQuestionCount:    '4 題',
    laborBreadcrumbRoot:   '🏛 權益速查',
    laborRead:             '✅ 已讀',

    // 分類名稱
    laborCategoryWage:     '薪資',
    laborCategoryHours:    '工時',
    laborCategoryLeave:    '休假',
    laborCategorySafety:   '人身安全',
    laborCategoryDocument: '證件居留',
    laborCategoryOther:    '其他',

    // 合法判斷 badge
    laborLegal:            '✅ 合法',
    laborIllegal:          '❌ 違法',
    laborNeedCheck:        '⚠️ 需確認',

    // 證據提醒
    laborEvidenceTitle:    '💡 請先保留以下證據',

    // 行動按鈕
    laborCall1955:         '📞 撥打 1955',
    laborContactLAF:       '🌐 聯絡法扶基金會',

    // 通用
    btnClose: '關閉',
    btnSave: '儲存',
    btnNext: '下一步',
    msgLoading: '載入中…',
    msgError: '發生錯誤，請重試',

    // 問診卡模組
    symptomTitle:        '問診卡',
    symptomStep1Title:   '步驟 1/3　選擇不舒服的部位',
    symptomStep2Title:   '步驟 2/3　選擇症狀（最多 3 項）',
    symptomStep3Title:   '步驟 3/3　出示卡',
    symptomGroupGeneral: '一般症狀',
    symptomGroupPain:    '痛感類型',
    symptomSelectedCount:'已選 {n}/3',
    symptomBtnNext:      '下一步',
    symptomBtnBack:      '上一步',
    symptomBtnGenerate:  '生成出示卡',
    symptomBtnReset:     '🔄 重新選擇',
    symptomBtnCopy:      '📋 複製文字',
    symptomCardTitle:    '🏥 請將此卡出示給醫護人員',
    symptomCardNative:   '您的症狀（母語）',
    symptomCardZh:       '我的症狀（中文）',
    symptomUrgentAlert:  '⚠️ 請優先處理 / Please Prioritize',
    symptomCopied:       '已複製！',
    symptomHistory:      '問診紀錄',

    // 資源地圖模組
    mapTitle:            '🗺 友善資源地圖',
    mapLocateBtn:        '📍 定位我的位置',
    mapFilterAll:        '全部',
    mapFilterMedical:    '🏥 醫療',
    mapFilterLegal:      '⚖️ 法扶',
    mapFilterNewcomer:   '🏠 服務中心',
    mapNearby:           '最近機構',
    mapOffline:          '地圖載入失敗，請確認網路連線',

    // 地標遊戲模組（Sub-Task 7）
    gameToastTitle:      '🎮 附近有任務！',
    gameStart:           '開始 ▶',
    gameClose:           '✕',
    gameCorrect:         '✅ 答對了！',
    gameWrong:           '❌ 再想想',
    gameScore:           '答對 {correct}/{total} 題',
    gameSortInstruct:    '請用 ⬆️ ⬇️ 調整順序，再按「確認排序」',
    gameFillInstruct:    '選擇正確的詞填入空格',
    gameMatchInstruct:   '這個圖示代表什麼？請選擇正確答案',
    gameConfirmSort:     '確認排序',
    gameLandmarkName:    '📍 地標任務',

    // Sub-Task 8 — 成就機制 & 排名系統
    achievementsTitle:   '成就',
    achUnlockedAt:       '解鎖於',
    achLocked:           '未解鎖',
    rankUpTitle:         '段位升級！',

    // 10 個成就名稱
    ach_first_game:     '初次出賽',
    ach_first_card:     '初次問診',
    ach_labor_explorer: '勞工探索家',
    ach_labor_master:   '勞工達人',
    ach_landmark_3:     '三站通',
    ach_landmark_all:   '地標全覽',
    ach_score_40:       '穩健成長',
    ach_score_80:       '高手境界',
    ach_streak_3:       '連續挑戰',
    ach_perfect_game:   '完美作答',
  },

  en: {
    langScreenTitle: 'Choose Your Language',
    langScreenSubtitle: 'You can change this anytime on the home screen',

    authWelcome: 'Welcome to MigrantCare',
    authSubtitle: 'Kaohsiung Migrant-Friendly Assistant',
    loginTitle: 'Select Account',
    registerTitle: 'Create Account',
    btnLogin: 'Log In',
    btnRegister: 'Create New Account',
    btnConfirm: 'Confirm',
    btnBack: 'Back',
    inputNickname: 'Nickname (2–20 chars)',
    inputPin: '4-digit PIN',
    inputPinConfirm: 'Confirm PIN',
    labelIdentity: 'Your Identity',
    identityWorker: 'Migrant Worker',
    identityNewcomer: 'New Resident',
    identityOther: 'Other',
    labelAvatar: 'Choose Avatar',
    msgPinMismatch: 'PINs do not match, please try again',
    msgNicknameRequired: 'Please enter a nickname (2–20 chars)',
    msgPinRequired: 'Please enter a 4-digit PIN',
    msgLoginFail: 'Incorrect PIN, please try again',

    // 勞工權益速查模組
    laborTitle:            '🏛 Labor Rights',
    laborSelectCategory:   'Select a Category',
    laborQuestionCount:    '4 Questions',
    laborBreadcrumbRoot:   '🏛 Rights',
    laborRead:             '✅ Read',

    laborCategoryWage:     'Wages',
    laborCategoryHours:    'Working Hours',
    laborCategoryLeave:    'Leave',
    laborCategorySafety:   'Personal Safety',
    laborCategoryDocument: 'Documents & Residency',
    laborCategoryOther:    'Other',

    laborLegal:            '✅ Legal',
    laborIllegal:          '❌ Illegal',
    laborNeedCheck:        '⚠️ Needs Verification',

    laborEvidenceTitle:    '💡 Keep the following evidence',

    laborCall1955:         '📞 Call 1955',
    laborContactLAF:       '🌐 Contact LAF',

    tabHome: 'Home',
    tabMedical: 'Medical',
    tabLabor: 'Rights',
    tabMap: 'Map',
    tabTranslate: 'Translate',

    // Translation Module
    translateSubtitle:   'Doctor speaks Chinese ↔ Migrant speaks native language, real-time translation',
    translateHint:       'Press the button below to start speaking',
    translateDoctorBtn:  'Medical Staff Speak',
    translatePatientBtn: 'Migrant Worker Speak',

    homeGreeting: 'Hello',
    homeFamiliarityLabel: 'Familiarity',
    homeRankLabel: 'Rank',
    homeGameSwitch: 'Landmark Game',
    homeGameOn: 'On',
    homeGameOff: 'Off',

    rankSprout:  'Sprout',
    rankGrowing: 'Growing',
    rankSteady:  'Steady',
    rankSkilled: 'Skilled',
    rankExpert:  'Expert',

    homeStatLaborLabel:   'Labor Rights',
    homeStatLaborValue:   '{n}/24 read',
    homeStatSymptomLabel: 'Medical Card',
    homeStatSymptomValue: 'Used {n} times',
    homeStatLandmarkLabel:'Landmark Game',
    homeStatLandmarkValue:'Visited {n} landmarks',
    homeLastLocation:     'Last Location',
    homeNoLocation:       'Not recorded yet',
    homeQuickEntry:       'Quick Access',
    homeLogout:           'Log Out',
    homeLogoutConfirm:    'Are you sure you want to log out?',

    btnClose: 'Close',
    btnSave: 'Save',
    btnNext: 'Next',
    msgLoading: 'Loading…',
    msgError: 'An error occurred, please retry',

    // Medical Card Module
    symptomTitle:        'Medical Card',
    symptomStep1Title:   'Step 1/3  Choose the uncomfortable area',
    symptomStep2Title:   'Step 2/3  Select symptoms (up to 3)',
    symptomStep3Title:   'Step 3/3  Show Card',
    symptomGroupGeneral: 'General Symptoms',
    symptomGroupPain:    'Pain Type',
    symptomSelectedCount:'Selected {n}/3',
    symptomBtnNext:      'Next',
    symptomBtnBack:      'Back',
    symptomBtnGenerate:  'Generate Card',
    symptomBtnReset:     '🔄 Start Over',
    symptomBtnCopy:      '📋 Copy Text',
    symptomCardTitle:    '🏥 Please show this card to medical staff',
    symptomCardNative:   'Your symptoms (native language)',
    symptomCardZh:       'My symptoms (Chinese)',
    symptomUrgentAlert:  '⚠️ Please Prioritize',
    symptomCopied:       'Copied!',
    symptomHistory:      'Medical History',

    // Map Module
    mapTitle:            '🗺 Friendly Resource Map',
    mapLocateBtn:        '📍 Locate My Position',
    mapFilterAll:        'All',
    mapFilterMedical:    '🏥 Medical',
    mapFilterLegal:      '⚖️ Legal Aid',
    mapFilterNewcomer:   '🏠 Service Center',
    mapNearby:           'Nearby Locations',
    mapOffline:          'Map failed to load. Please check your connection.',

    // Landmark Game Module (Sub-Task 7)
    gameToastTitle:      '🎮 Nearby mission!',
    gameStart:           'Start ▶',
    gameClose:           '✕',
    gameCorrect:         '✅ Correct!',
    gameWrong:           '❌ Try again',
    gameScore:           '{correct}/{total} correct',
    gameSortInstruct:    'Use ⬆️ ⬇️ to reorder, then tap "Confirm Order"',
    gameFillInstruct:    'Choose the correct word to fill in the blank',
    gameMatchInstruct:   'What does this icon represent? Choose the correct answer',
    gameConfirmSort:     'Confirm Order',
    gameLandmarkName:    '📍 Landmark Mission',

    // Sub-Task 8 — Achievements & Rank System
    achievementsTitle:   'Achievements',
    achUnlockedAt:       'Unlocked on',
    achLocked:           'Locked',
    rankUpTitle:         'Rank Up!',

    ach_first_game:     'First Game',
    ach_first_card:     'First Medical Card',
    ach_labor_explorer: 'Labor Explorer',
    ach_labor_master:   'Labor Master',
    ach_landmark_3:     'Triple Landmark',
    ach_landmark_all:   'All Landmarks',
    ach_score_40:       'Steady Growth',
    ach_score_80:       'Expert Level',
    ach_streak_3:       'Streak Challenge',
    ach_perfect_game:   'Perfect Answer',
  },

  id: {
    langScreenTitle: 'Pilih Bahasa Anda',
    langScreenSubtitle: 'Anda dapat mengubahnya kapan saja di halaman utama',

    authWelcome: 'Selamat Datang di MigrantCare',
    authSubtitle: 'Asisten Ramah Migran Kaohsiung',
    loginTitle: 'Pilih Akun',
    registerTitle: 'Buat Akun',
    btnLogin: 'Masuk',
    btnRegister: 'Buat Akun Baru',
    btnConfirm: 'Konfirmasi',
    btnBack: 'Kembali',
    inputNickname: 'Nama panggilan (2–20 karakter)',
    inputPin: 'PIN 4 digit',
    inputPinConfirm: 'Konfirmasi PIN',
    labelIdentity: 'Identitas Anda',
    identityWorker: 'Pekerja Migran',
    identityNewcomer: 'Penduduk Baru',
    identityOther: 'Lainnya',
    labelAvatar: 'Pilih Avatar',
    msgPinMismatch: 'PIN tidak cocok, coba lagi',
    msgNicknameRequired: 'Masukkan nama panggilan (2–20 karakter)',
    msgPinRequired: 'Masukkan PIN 4 digit',
    msgLoginFail: 'PIN salah, coba lagi',

    // Modul Hak Kerja
    laborTitle:            '🏛 Hak Kerja',
    laborSelectCategory:   'Pilih Kategori',
    laborQuestionCount:    '4 Pertanyaan',
    laborBreadcrumbRoot:   '🏛 Hak Kerja',
    laborRead:             '✅ Sudah Dibaca',

    laborCategoryWage:     'Gaji',
    laborCategoryHours:    'Jam Kerja',
    laborCategoryLeave:    'Cuti',
    laborCategorySafety:   'Keselamatan Pribadi',
    laborCategoryDocument: 'Dokumen & Izin Tinggal',
    laborCategoryOther:    'Lainnya',

    laborLegal:            '✅ Sah',
    laborIllegal:          '❌ Melanggar Hukum',
    laborNeedCheck:        '⚠️ Perlu Verifikasi',

    laborEvidenceTitle:    '💡 Simpan bukti berikut',

    laborCall1955:         '📞 Hubungi 1955',
    laborContactLAF:       '🌐 Hubungi LAF',

    tabHome: 'Beranda',
    tabMedical: 'Kartu Medis',
    tabLabor: 'Hak Kerja',
    tabMap: 'Peta Layanan',
    tabTranslate: 'Terjemahan',

    // Modul Penerjemahan
    translateSubtitle:   'Dokter berbicara Mandarin ↔ Pekerja migran berbicara bahasa ibu, terjemahan langsung',
    translateHint:       'Tekan tombol di bawah untuk mulai berbicara',
    translateDoctorBtn:  'Tenaga Medis Bicara',
    translatePatientBtn: 'Pekerja Migran Bicara',

    homeGreeting: 'Halo',
    homeFamiliarityLabel: 'Keakraban',
    homeRankLabel: 'Peringkat',
    homeGameSwitch: 'Permainan Landmark',
    homeGameOn: 'Aktif',
    homeGameOff: 'Nonaktif',

    rankSprout:  'Tunas',
    rankGrowing: 'Berkembang',
    rankSteady:  'Stabil',
    rankSkilled: 'Terampil',
    rankExpert:  'Ahli',

    homeStatLaborLabel:   'Hak Kerja',
    homeStatLaborValue:   '{n}/24 dibaca',
    homeStatSymptomLabel: 'Kartu Medis',
    homeStatSymptomValue: 'Digunakan {n} kali',
    homeStatLandmarkLabel:'Permainan Landmark',
    homeStatLandmarkValue:'Kunjungi {n} landmark',
    homeLastLocation:     'Lokasi Terakhir',
    homeNoLocation:       'Belum tercatat',
    homeQuickEntry:       'Akses Cepat',
    homeLogout:           'Keluar',
    homeLogoutConfirm:    'Apakah Anda yakin ingin keluar?',

    btnClose: 'Tutup',
    btnSave: 'Simpan',
    btnNext: 'Berikutnya',
    msgLoading: 'Memuat…',
    msgError: 'Terjadi kesalahan, coba lagi',

    // Modul Kartu Medis
    symptomTitle:        'Kartu Medis',
    symptomStep1Title:   'Langkah 1/3  Pilih bagian yang tidak nyaman',
    symptomStep2Title:   'Langkah 2/3  Pilih gejala (maks 3 item)',
    symptomStep3Title:   'Langkah 3/3  Kartu Peraga',
    symptomGroupGeneral: 'Gejala Umum',
    symptomGroupPain:    'Jenis Nyeri',
    symptomSelectedCount:'Dipilih {n}/3',
    symptomBtnNext:      'Berikutnya',
    symptomBtnBack:      'Kembali',
    symptomBtnGenerate:  'Buat Kartu',
    symptomBtnReset:     '🔄 Pilih Ulang',
    symptomBtnCopy:      '📋 Salin Teks',
    symptomCardTitle:    '🏥 Tunjukkan kartu ini kepada tenaga medis',
    symptomCardNative:   'Gejala Anda (bahasa ibu)',
    symptomCardZh:       'Gejala saya (Bahasa Mandarin)',
    symptomUrgentAlert:  '⚠️ Tolong Prioritaskan / Please Prioritize',
    symptomCopied:       'Tersalin!',
    symptomHistory:      'Riwayat Konsultasi',

    // Modul Peta
    mapTitle:            '🗺 Peta Sumber Ramah',
    mapLocateBtn:        '📍 Temukan Lokasi Saya',
    mapFilterAll:        'Semua',
    mapFilterMedical:    '🏥 Medis',
    mapFilterLegal:      '⚖️ Bantuan Hukum',
    mapFilterNewcomer:   '🏠 Pusat Layanan',
    mapNearby:           'Lokasi Terdekat',
    mapOffline:          'Peta gagal dimuat. Periksa koneksi internet Anda.',

    // Modul Permainan Landmark (Sub-Task 7)
    gameToastTitle:      '🎮 Ada misi di dekat Anda!',
    gameStart:           'Mulai ▶',
    gameClose:           '✕',
    gameCorrect:         '✅ Benar!',
    gameWrong:           '❌ Coba lagi',
    gameScore:           '{correct}/{total} benar',
    gameSortInstruct:    'Gunakan ⬆️ ⬇️ untuk mengatur urutan, lalu ketuk "Konfirmasi Urutan"',
    gameFillInstruct:    'Pilih kata yang tepat untuk mengisi bagian kosong',
    gameMatchInstruct:   'Ikon ini mewakili apa? Pilih jawaban yang benar',
    gameConfirmSort:     'Konfirmasi Urutan',
    gameLandmarkName:    '📍 Misi Landmark',

    // Sub-Task 8 — Pencapaian & Sistem Peringkat
    achievementsTitle:   'Pencapaian',
    achUnlockedAt:       'Dibuka pada',
    achLocked:           'Terkunci',
    rankUpTitle:         'Naik Peringkat!',

    ach_first_game:     'Permainan Pertama',
    ach_first_card:     'Kartu Medis Pertama',
    ach_labor_explorer: 'Penjelajah Hak Kerja',
    ach_labor_master:   'Ahli Hak Kerja',
    ach_landmark_3:     'Tiga Landmark',
    ach_landmark_all:   'Semua Landmark',
    ach_score_40:       'Pertumbuhan Stabil',
    ach_score_80:       'Level Ahli',
    ach_streak_3:       'Tantangan Beruntun',
    ach_perfect_game:   'Jawaban Sempurna',
  },

  vi: {
    langScreenTitle: 'Chọn ngôn ngữ của bạn',
    langScreenSubtitle: 'Bạn có thể thay đổi bất cứ lúc nào ở trang chính',

    authWelcome: 'Chào mừng đến MigrantCare',
    authSubtitle: 'Trợ lý thân thiện di dân Cao Hùng',
    loginTitle: 'Chọn tài khoản',
    registerTitle: 'Tạo tài khoản',
    btnLogin: 'Đăng nhập',
    btnRegister: 'Tạo tài khoản mới',
    btnConfirm: 'Xác nhận',
    btnBack: 'Quay lại',
    inputNickname: 'Biệt danh (2–20 ký tự)',
    inputPin: 'PIN 4 chữ số',
    inputPinConfirm: 'Xác nhận PIN',
    labelIdentity: 'Danh tính của bạn',
    identityWorker: 'Lao động di trú',
    identityNewcomer: 'Cư dân mới',
    identityOther: 'Khác',
    labelAvatar: 'Chọn hình đại diện',
    msgPinMismatch: 'PIN không khớp, vui lòng thử lại',
    msgNicknameRequired: 'Vui lòng nhập biệt danh (2–20 ký tự)',
    msgPinRequired: 'Vui lòng nhập PIN 4 chữ số',
    msgLoginFail: 'PIN không đúng, vui lòng thử lại',

    // Mô-đun Quyền Lao Động
    laborTitle:            '🏛 Quyền Lao Động',
    laborSelectCategory:   'Chọn danh mục',
    laborQuestionCount:    '4 câu hỏi',
    laborBreadcrumbRoot:   '🏛 Quyền lợi',
    laborRead:             '✅ Đã đọc',

    laborCategoryWage:     'Tiền lương',
    laborCategoryHours:    'Giờ làm việc',
    laborCategoryLeave:    'Nghỉ phép',
    laborCategorySafety:   'An toàn cá nhân',
    laborCategoryDocument: 'Giấy tờ & Cư trú',
    laborCategoryOther:    'Khác',

    laborLegal:            '✅ Hợp pháp',
    laborIllegal:          '❌ Vi phạm pháp luật',
    laborNeedCheck:        '⚠️ Cần xác nhận',

    laborEvidenceTitle:    '💡 Vui lòng giữ bằng chứng sau',

    laborCall1955:         '📞 Gọi 1955',
    laborContactLAF:       '🌐 Liên hệ LAF',

    tabHome: 'Trang chủ',
    tabMedical: 'Thẻ y tế',
    tabLabor: 'Quyền lợi',
    tabMap: 'Bản đồ',
    tabTranslate: 'Phiên dịch',

    // Mô-đun Phiên Dịch
    translateSubtitle:   'Bác sĩ nói tiếng Trung ↔ Lao động nói tiếng mẹ đẻ, dịch trực tiếp',
    translateHint:       'Nhấn nút bên dưới để bắt đầu nói',
    translateDoctorBtn:  'Nhân viên y tế nói',
    translatePatientBtn: 'Lao động di trú nói',

    homeGreeting: 'Xin chào',
    homeFamiliarityLabel: 'Mức độ quen thuộc',
    homeRankLabel: 'Hạng',
    homeGameSwitch: 'Trò chơi địa danh',
    homeGameOn: 'Bật',
    homeGameOff: 'Tắt',

    rankSprout:  'Mầm non',
    rankGrowing: 'Đang phát triển',
    rankSteady:  'Ổn định',
    rankSkilled: 'Thành thạo',
    rankExpert:  'Chuyên gia',

    homeStatLaborLabel:   'Quyền lao động',
    homeStatLaborValue:   'Đọc {n}/24',
    homeStatSymptomLabel: 'Thẻ y tế',
    homeStatSymptomValue: 'Đã dùng {n} lần',
    homeStatLandmarkLabel:'Trò chơi địa danh',
    homeStatLandmarkValue:'Thăm {n} địa danh',
    homeLastLocation:     'Vị trí gần nhất',
    homeNoLocation:       'Chưa ghi lại',
    homeQuickEntry:       'Lối vào nhanh',
    homeLogout:           'Đăng xuất',
    homeLogoutConfirm:    'Bạn có chắc muốn đăng xuất không?',

    btnClose: 'Đóng',
    btnSave: 'Lưu',
    btnNext: 'Tiếp theo',
    msgLoading: 'Đang tải…',
    msgError: 'Có lỗi xảy ra, vui lòng thử lại',

    // Mo-dun The Y Te
    symptomTitle:        'Thẻ Y Tế',
    symptomStep1Title:   'Bước 1/3  Chọn vùng khó chịu',
    symptomStep2Title:   'Bước 2/3  Chọn triệu chứng (tối đa 3)',
    symptomStep3Title:   'Bước 3/3  Thẻ Hiển Thị',
    symptomGroupGeneral: 'Triệu Chứng Chung',
    symptomGroupPain:    'Loại Đau',
    symptomSelectedCount:'Đã chọn {n}/3',
    symptomBtnNext:      'Tiếp theo',
    symptomBtnBack:      'Quay lại',
    symptomBtnGenerate:  'Tạo thẻ',
    symptomBtnReset:     '🔄 Chọn lại',
    symptomBtnCopy:      '📋 Sao chép',
    symptomCardTitle:    '🏥 Vui lòng đưa thẻ này cho nhân viên y tế',
    symptomCardNative:   'Triệu chứng của bạn (tiếng mẹ đẻ)',
    symptomCardZh:       'Triệu chứng của tôi (tiếng Trung)',
    symptomUrgentAlert:  '⚠️ Xin ưu tiên xử lý / Please Prioritize',
    symptomCopied:       'Đã sao chép!',
    symptomHistory:      'Lịch Sử Khám',

    // Mô-đun Bản Đồ
    mapTitle:            '🗺 Bản Đồ Tài Nguyên Thân Thiện',
    mapLocateBtn:        '📍 Xác Định Vị Trí Của Tôi',
    mapFilterAll:        'Tất cả',
    mapFilterMedical:    '🏥 Y tế',
    mapFilterLegal:      '⚖️ Hỗ trợ Pháp lý',
    mapFilterNewcomer:   '🏠 Trung tâm Dịch vụ',
    mapNearby:           'Địa điểm Gần Nhất',
    mapOffline:          'Tải bản đồ thất bại. Vui lòng kiểm tra kết nối.',

    // Mô-đun Trò Chơi Địa Danh (Sub-Task 7)
    gameToastTitle:      '🎮 Có nhiệm vụ gần đây!',
    gameStart:           'Bắt đầu ▶',
    gameClose:           '✕',
    gameCorrect:         '✅ Đúng rồi!',
    gameWrong:           '❌ Thử lại',
    gameScore:           'Đúng {correct}/{total} câu',
    gameSortInstruct:    'Dùng ⬆️ ⬇️ để sắp xếp rồi nhấn "Xác nhận thứ tự"',
    gameFillInstruct:    'Chọn từ đúng để điền vào chỗ trống',
    gameMatchInstruct:   'Biểu tượng này đại diện cho gì? Chọn câu trả lời đúng',
    gameConfirmSort:     'Xác nhận thứ tự',
    gameLandmarkName:    '📍 Nhiệm vụ Địa danh',

    // Sub-Task 8 — Thành tích & Hệ thống Hạng
    achievementsTitle:   'Thành tích',
    achUnlockedAt:       'Mở khóa lúc',
    achLocked:           'Chưa mở',
    rankUpTitle:         'Lên Hạng!',

    ach_first_game:     'Lần chơi đầu tiên',
    ach_first_card:     'Thẻ y tế đầu tiên',
    ach_labor_explorer: 'Nhà khám phá quyền lao động',
    ach_labor_master:   'Chuyên gia quyền lao động',
    ach_landmark_3:     'Ba địa danh',
    ach_landmark_all:   'Tất cả địa danh',
    ach_score_40:       'Tăng trưởng ổn định',
    ach_score_80:       'Cấp độ chuyên gia',
    ach_streak_3:       'Thử thách liên tiếp',
    ach_perfect_game:   'Trả lời hoàn hảo',
  },

  th: {
    langScreenTitle: 'เลือกภาษาของคุณ',
    langScreenSubtitle: 'คุณสามารถเปลี่ยนได้ทุกเมื่อที่หน้าหลัก',

    authWelcome: 'ยินดีต้อนรับสู่ MigrantCare',
    authSubtitle: 'ผู้ช่วยเป็นมิตรแรงงานข้ามชาติเกาสง',
    loginTitle: 'เลือกบัญชี',
    registerTitle: 'สร้างบัญชี',
    btnLogin: 'เข้าสู่ระบบ',
    btnRegister: 'สร้างบัญชีใหม่',
    btnConfirm: 'ยืนยัน',
    btnBack: 'กลับ',
    inputNickname: 'ชื่อเล่น (2–20 ตัวอักษร)',
    inputPin: 'PIN 4 หลัก',
    inputPinConfirm: 'ยืนยัน PIN',
    labelIdentity: 'อัตลักษณ์ของคุณ',
    identityWorker: 'แรงงานข้ามชาติ',
    identityNewcomer: 'ผู้อยู่อาศัยใหม่',
    identityOther: 'อื่นๆ',
    labelAvatar: 'เลือกอวตาร',
    msgPinMismatch: 'PIN ไม่ตรงกัน กรุณาลองอีกครั้ง',
    msgNicknameRequired: 'กรุณาใส่ชื่อเล่น (2–20 ตัวอักษร)',
    msgPinRequired: 'กรุณาใส่ PIN 4 หลัก',
    msgLoginFail: 'PIN ไม่ถูกต้อง กรุณาลองอีกครั้ง',

    // โมดูลสิทธิแรงงาน
    laborTitle:            '🏛 สิทธิแรงงาน',
    laborSelectCategory:   'เลือกหมวดหมู่',
    laborQuestionCount:    '4 คำถาม',
    laborBreadcrumbRoot:   '🏛 สิทธิ์',
    laborRead:             '✅ อ่านแล้ว',

    laborCategoryWage:     'เงินเดือน',
    laborCategoryHours:    'ชั่วโมงทำงาน',
    laborCategoryLeave:    'วันลา',
    laborCategorySafety:   'ความปลอดภัยส่วนตัว',
    laborCategoryDocument: 'เอกสาร & การพำนัก',
    laborCategoryOther:    'อื่นๆ',

    laborLegal:            '✅ ถูกกฎหมาย',
    laborIllegal:          '❌ ผิดกฎหมาย',
    laborNeedCheck:        '⚠️ ต้องตรวจสอบ',

    laborEvidenceTitle:    '💡 โปรดเก็บหลักฐานต่อไปนี้',

    laborCall1955:         '📞 โทร 1955',
    laborContactLAF:       '🌐 ติดต่อ LAF',

    tabHome: 'หน้าหลัก',
    tabMedical: 'บัตรการแพทย์',
    tabLabor: 'สิทธิแรงงาน',
    tabMap: 'แผนที่',
    tabTranslate: 'แปลภาษา',

    // โมดูลแปลภาษา
    translateSubtitle:   'แพทย์พูดภาษาจีน ↔ แรงงานพูดภาษาแม่ แปลแบบเรียลไทม์',
    translateHint:       'กดปุ่มด้านล่างเพื่อเริ่มพูด',
    translateDoctorBtn:  'บุคลากรทางการแพทย์พูด',
    translatePatientBtn: 'แรงงานข้ามชาติพูด',

    homeGreeting: 'สวัสดี',
    homeFamiliarityLabel: 'ความคุ้นเคย',
    homeRankLabel: 'ระดับ',
    homeGameSwitch: 'เกมสถานที่สำคัญ',
    homeGameOn: 'เปิด',
    homeGameOff: 'ปิด',

    rankSprout:  'หน่อไม้',
    rankGrowing: 'กำลังเติบโต',
    rankSteady:  'มั่นคง',
    rankSkilled: 'ชำนาญ',
    rankExpert:  'ผู้เชี่ยวชาญ',

    homeStatLaborLabel:   'สิทธิแรงงาน',
    homeStatLaborValue:   'อ่าน {n}/24',
    homeStatSymptomLabel: 'บัตรการแพทย์',
    homeStatSymptomValue: 'ใช้ {n} ครั้ง',
    homeStatLandmarkLabel:'เกมสถานที่',
    homeStatLandmarkValue:'เยี่ยม {n} สถานที่',
    homeLastLocation:     'ตำแหน่งล่าสุด',
    homeNoLocation:       'ยังไม่ได้บันทึก',
    homeQuickEntry:       'ทางเข้าด่วน',
    homeLogout:           'ออกจากระบบ',
    homeLogoutConfirm:    'คุณแน่ใจหรือไม่ว่าต้องการออกจากระบบ?',

    btnClose: 'ปิด',
    btnSave: 'บันทึก',
    btnNext: 'ถัดไป',
    msgLoading: 'กำลังโหลด…',
    msgError: 'เกิดข้อผิดพลาด กรุณาลองใหม่',

    // โมดูลบัตรการแพทย์
    symptomTitle:        'บัตรการแพทย์',
    symptomStep1Title:   'ขั้นที่ 1/3  เลือกส่วนที่ไม่สบาย',
    symptomStep2Title:   'ขั้นที่ 2/3  เลือกอาการ (สูงสุด 3 รายการ)',
    symptomStep3Title:   'ขั้นที่ 3/3  บัตรแสดง',
    symptomGroupGeneral: 'อาการทั่วไป',
    symptomGroupPain:    'ประเภทความเจ็บปวด',
    symptomSelectedCount:'เลือกแล้ว {n}/3',
    symptomBtnNext:      'ถัดไป',
    symptomBtnBack:      'ย้อนกลับ',
    symptomBtnGenerate:  'สร้างบัตร',
    symptomBtnReset:     '🔄 เลือกใหม่',
    symptomBtnCopy:      '📋 คัดลอก',
    symptomCardTitle:    '🏥 กรุณาแสดงบัตรนี้แก่เจ้าหน้าที่ทางการแพทย์',
    symptomCardNative:   'อาการของคุณ (ภาษาแม่)',
    symptomCardZh:       'อาการของฉัน (ภาษาจีน)',
    symptomUrgentAlert:  '⚠️ กรุณาจัดการด่วน / Please Prioritize',
    symptomCopied:       'คัดลอกแล้ว!',
    symptomHistory:      'ประวัติการปรึกษา',

    // โมดูลแผนที่
    mapTitle:            '🗺 แผนที่ทรัพยากรที่เป็นมิตร',
    mapLocateBtn:        '📍 ระบุตำแหน่งของฉัน',
    mapFilterAll:        'ทั้งหมด',
    mapFilterMedical:    '🏥 การแพทย์',
    mapFilterLegal:      '⚖️ ความช่วยเหลือทางกฎหมาย',
    mapFilterNewcomer:   '🏠 ศูนย์บริการ',
    mapNearby:           'สถานที่ใกล้เคียง',
    mapOffline:          'โหลดแผนที่ล้มเหลว กรุณาตรวจสอบการเชื่อมต่อ',

    // โมดูลเกมสถานที่สำคัญ (Sub-Task 7)
    gameToastTitle:      '🎮 มีภารกิจใกล้เคียง!',
    gameStart:           'เริ่ม ▶',
    gameClose:           '✕',
    gameCorrect:         '✅ ถูกต้อง!',
    gameWrong:           '❌ ลองอีกครั้ง',
    gameScore:           'ตอบถูก {correct}/{total} ข้อ',
    gameSortInstruct:    'ใช้ ⬆️ ⬇️ จัดลำดับ แล้วกด "ยืนยันลำดับ"',
    gameFillInstruct:    'เลือกคำที่ถูกต้องเพื่อเติมในช่องว่าง',
    gameMatchInstruct:   'ไอคอนนี้แทนอะไร? เลือกคำตอบที่ถูกต้อง',
    gameConfirmSort:     'ยืนยันลำดับ',
    gameLandmarkName:    '📍 ภารกิจสถานที่สำคัญ',

    // Sub-Task 8 — ความสำเร็จ & ระบบอันดับ
    achievementsTitle:   'ความสำเร็จ',
    achUnlockedAt:       'ปลดล็อกเมื่อ',
    achLocked:           'ยังไม่ปลดล็อก',
    rankUpTitle:         'เลื่อนระดับ!',

    ach_first_game:     'เล่นครั้งแรก',
    ach_first_card:     'บัตรการแพทย์ครั้งแรก',
    ach_labor_explorer: 'นักสำรวจสิทธิแรงงาน',
    ach_labor_master:   'ผู้เชี่ยวชาญสิทธิแรงงาน',
    ach_landmark_3:     'สามสถานที่',
    ach_landmark_all:   'ครบทุกสถานที่',
    ach_score_40:       'การเติบโตที่มั่นคง',
    ach_score_80:       'ระดับผู้เชี่ยวชาญ',
    ach_streak_3:       'ความท้าทายต่อเนื่อง',
    ach_perfect_game:   'ตอบได้สมบูรณ์แบบ',
  },
};
